{{- if .Values.jwt.defaultUrlMacPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.defaultUrlMacPrivateKey.name }}
  labels:
    app: {{ template "traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.key: {{ .Values.jwt.defaultUrlMacPrivateKey.value }}
{{- end }}
