{{- if .Values.jwt.defaultUrlMacClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.defaultUrlMacClientSecret.name }}
  labels:
    app: {{ template "traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  client.secret: {{ .Values.jwt.defaultUrlMacClientSecret.value }}
{{- end }}
